export const personal = [
  {
   "clave" : '',
  "docente": "Ayuso Cervera Jesús Emmanuel ",
   "horasMinimas": 15,
   "horasMaximas": 17,
   "lunes":     [15,21],
   "martes":    [15,21],
   "miercoles": [15,21],
   "jueves":    [15,21],
   "viernes":   [15,20]
  },
  {
   "clave" : '',
    "docente": "Cab Chan José Ramón ",
   "horasMinimas": 4,
   "horasMaximas": 5,
   "lunes":     [8,16],
   "martes":    [8,16],
   "miercoles": [8,16],
   "jueves":    [8,16],
   "viernes":   [8,16]
  },
  {
   "clave" : '',
    "docente": "Carpizo Acuña Cecilio Román ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [7,15],
   "martes":    [7,15],
   "miercoles": [7,15],
   "jueves":    [7,15],
   "viernes":   [7,15]
  },
  {
   "clave" : '',
    "docente": "Cervera Castro Aracely del Carmen ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [12,20],
   "martes":    [12,20],
   "miercoles": [12,20],
   "jueves":    [12,20],
   "viernes":   [11,19]
  },
  {
   "clave" : '',
    "docente": "Cervera Palí Humberto",
   "horasMinimas": 4,
   "horasMaximas": 5,
   "lunes":     [8,16],
   "martes":    [8,16],
   "miercoles": [8,16],
   "jueves":    [8,16],
   "viernes":   [8,16]
  },
  {
   "clave" : '',
    "docente": "Cervera Sabido Mirna Irene",
   "horasMinimas": 16,
   "horasMaximas": 16,
   "lunes":     [12,16],
   "martes":    [12,16],
   "miercoles": [12,16],
   "jueves":    [12,16]
  },
  {
   "clave" : '',
    "docente": "Chuc López Jorge Luis",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [8,16],
   "martes":    [8,16],
   "miercoles": [8,16],
   "jueves":    [8,16],
   "viernes":   [8,16]
  },
  {
   "clave" : '',
    "docente": "Cruz Pinzón Wilberth Eduardo ",
   "horasMinimas": 12,
   "horasMaximas": 16,
   "lunes":     [7,11],
   "martes":    [7,11],
   "miercoles": [7,11],
   "jueves":    [7,11],
   "viernes":   [7,11]
  },
  {
   "clave" : '',
    "docente": "De la Cruz Muñoz Vicente",
   "horasMinimas": 4,
   "horasMaximas": 5,
   "lunes":     [7,15],
   "martes":    [7,15],
   "miercoles": [7,15],
   "jueves":    [7,15],
   "viernes":   [7,15]
  },
  {
   "clave" : '',
    "docente": "Flores Redondo Salvador Adrián ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [9,17],
   "martes":    [9,17],
   "miercoles": [9,17],
   "jueves":    [9,17],
   "viernes":   [9,17]
  },
  {
   "clave" : '',
    "docente": "García Reyes Alicia Guadalupe ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [8,16],
   "martes":    [8,16],
   "miercoles": [8,16],
   "jueves":    [8,16],
   "viernes":   [8,16]
  },
  {
    "clave" : '',
    "docente": "Hernández Ancona Josefa del Carmen ",
    "horasMinimas": 20,
    "horasMaximas": 24,
    "lunes":     [8,16],
    "martes":    [8,16],
    "miercoles": [8,16],
    "jueves":    [8,16],
    "viernes":   [8,16]
  },
  {
    "clave" : '398',
    "docente": "Hernández Meza Manuel Enrique ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [8,16],
   "martes":    [8,16],
   "miercoles": [8,16],
   "jueves":    [8,16],
   "viernes":   [8,16]
  },
  {
   "clave" : '000',
    "docente": "Lanz Vera Iván A.",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [9,17],
   "martes":    [9,17],
   "miercoles": [9,17],
   "jueves":    [9,17],
   "viernes":   [9,17]
  },
  {
   "clave" : '',
    "docente": "May Salazar Laura",
   "horasMinimas": 12,
   "horasMaximas": 16,
   "lunes":     [12,16],
   "martes":    [12,16],
   "miercoles": [12,16],
   "jueves":    [12,16],
   "viernes":   [12,16]
  },
  {
   "clave" : '',
    "docente": "Moncada Bolón Juan Jesús",
   "horasMinimas": 10,
   "horasMaximas": 10,
   "martes":    [7,12],
   "jueves":    [7,12]
  },
  {
   "clave" : '',
    "docente": "Ortiz Arjona Jonathan Heli ",
   "horasMinimas": 8,
   "horasMaximas": 10,
   "lunes":     [8,16],
   "martes":    [8,16],
   "miercoles": [8,16],
   "jueves":    [8,16],
   "viernes":   [8,16]
  },
  {
   "clave" : '',
    "docente": "Pacheco Can Elías Elías Gabriel Fidel ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [8,16],
   "martes":    [8,16],
   "miercoles": [8,16],
   "jueves":    [8,16],
   "viernes":   [8,16]
  },
  {
   "clave" : '',
    "docente": "Pacheco Can Eliceo Eliceo Manuel Martín",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [7,15],
   "martes":    [7,15],
   "miercoles": [7,15],
   "jueves":    [7,15],
   "viernes":   [7,15]
  },
  {
   "clave" : '',
    "docente": "Ramírez Santamaria Jorge Enrique ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [7,15],
   "martes":    [7,15],
   "miercoles": [7,15],
   "jueves":    [7,15],
   "viernes":   [7,15]
  },
  {
   "clave" : '',
    "docente": "Seca Escalante Rosa Mauricia ",
   "horasMinimas": 16,
   "horasMaximas": 20,
   "lunes":     [7,13],
   "martes":    [7,13],
   "miercoles": [7,13],
   "jueves":    [7,13],
   "viernes":   [7,13]
  },
  {
   "clave" : '',
    "docente": "Soler Gonzalez  Cristian",
   "horasMinimas": 4,
   "horasMaximas": 5,
   "lunes":     [8,16],
   "martes":    [8,16],
   "miercoles": [8,16],
   "jueves":    [8,16],
   "viernes":   [8,16]
  },
  {
   "clave" : '',
    "docente": "Suárez Améndola Rosario de Fátima ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [7,15],
   "martes":    [7,15],
   "miercoles": [7,15],
   "jueves":    [7,15],
   "viernes":   [7,15]
  },
  {
   "clave" : '',
    "docente": "Vilchis Fuentes Julio Cesar ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [12,20],
   "martes":    [12,20],
   "miercoles": [12,20],
   "jueves":    [12,20],
   "viernes":   [12,20]
  },
  {
   "clave" : '',
    "docente": "Zetina Saravia Rubén Martín ",
   "horasMinimas": 20,
   "horasMaximas": 24,
   "lunes":     [13,21],
   "martes":    [13,21],
   "miercoles": [13,21],
   "jueves":    [13,21],
   "viernes":   [13,21]
  }
 ]

 export const reticula = [
  {
   "semestre": 1,
   "asignatura": "Cálculo diferencial",
   "clave": "acf-0901",
   "horasTeoricas": 3,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 1,
   "asignatura": "Fundamentos de programación",
   "clave": "aed-1285",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 1,
   "asignatura": "Química",
   "clave": "aec-1058",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 1,
   "asignatura": "Matemáticas discretas",
   "clave": "aef-1041",
   "horasTeoricas": 3,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 1,
   "asignatura": "Fundamentos de investigación",
   "clave": "acc-0906",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 1,
   "asignatura": "Física general",
   "clave": "scf-1006",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 1,
   "asignatura": "Taller de ética",
   "clave": "aca-0907",
   "horasTeoricas": 0,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 2,
   "asignatura": "Cálculo integral",
   "clave": "acf-0902",
   "horasTeoricas": 3,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 2,
   "asignatura": "Programación orientada a objetos",
   "clave": "aed-1286",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 2,
   "asignatura": "Álgebra lineal",
   "clave": "acf-0903",
   "horasTeoricas": 3,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 2,
   "asignatura": "Probabilidad y estadísticas",
   "clave": "aef-1052",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 2,
   "asignatura": "Principios eléctricos y aplicaciones",
   "clave": "scd-1018",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 2,
   "asignatura": "Arquitectura de computadoras",
   "clave": "scd-1003",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 3,
   "asignatura": "Cálculo vectorial",
   "clave": "acf-0904",
   "horasTeoricas": 3,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 3,
   "asignatura": "Tópicos avanzados de programación",
   "clave": "scd-1027",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 3,
   "asignatura": "Fundamentos de base de datos",
   "clave": "aef-1031",
   "horasTeoricas": 3,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 3,
   "asignatura": "Estructura de datos",
   "clave": "aed-1026",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 3,
   "asignatura": "Fundamentos de telecomunicaciones",
   "clave": "aec-1034",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 3,
   "asignatura": "Sistemas programables",
   "clave": "scd-1023",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 4,
   "asignatura": "Ecuaciones diferenciales",
   "clave": "acf-0905",
   "horasTeoricas": 3,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 4,
   "asignatura": "Fundamentos de ingeniería de software",
   "clave": "scc-1007",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 4,
   "asignatura": "Taller de base de datos",
   "clave": "sca-1025",
   "horasTeoricas": 0,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 4,
   "asignatura": "Métodos numéricos",
   "clave": "scc-1017",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 4,
   "asignatura": "Redes de computadoras",
   "clave": "scd-1021",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 4,
   "asignatura": "Sistemas operativos",
   "clave": "aec-1061",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 4,
   "asignatura": "Lenguajes de interfaz",
   "clave": "scc-1014",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 5,
   "asignatura": "Programación web",
   "clave": "aeb-1055",
   "horasTeoricas": 1,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 5,
   "asignatura": "Ingeniería de software",
   "clave": "scd-1011",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 5,
   "asignatura": "Administración de base de datos",
   "clave": "scb-1001",
   "horasTeoricas": 1,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 5,
   "asignatura": "Conmutación y enrutamiento de redes de datos",
   "clave": "scd-1004",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 5,
   "asignatura": "Investigación de operaciones",
   "clave": "scc-1013",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 5,
   "asignatura": "Taller de sistemas operativos",
   "clave": "sca-1026",
   "horasTeoricas": 0,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 6,
   "asignatura": "Lenguajes y autómatas I",
   "clave": "scd-1015",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 6,
   "asignatura": "Gestión de proyectos de software",
   "clave": "scg-1009",
   "horasTeoricas": 3,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 6,
   "asignatura": "Taller de administración",
   "clave": "sch-1024",
   "horasTeoricas": 1,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 6,
   "asignatura": "Frontend",
   "clave": "dad-2301",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": false,
   "especialidad": "desarrollo"
  },
  {
   "semestre": 6,
   "asignatura": "Base de datos no sql",
   "clave": "dah-2302",
   "horasTeoricas": 1,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": false,
   "especialidad": "desarrollo"
  },
  {
   "semestre": 6,
   "asignatura": "Administración de redes",
   "clave": "sca-1002",
   "horasTeoricas": 0,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 7,
   "asignatura": "Lenguajes y autómatas II",
   "clave": "scd-1016",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 7,
   "asignatura": "Taller de investigación I",
   "clave": "aca-0909",
   "horasTeoricas": 0,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 7,
   "asignatura": "Contabilidad financiera",
   "clave": "aec-1008",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 7,
   "asignatura": "Backend",
   "clave": "dad-2302",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": false,
   "especialidad": "desarrollo"
  },
  {
   "semestre": 7,
   "asignatura": "Simulación",
   "clave": "scd-1022",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 7,
   "asignatura": "Móviles",
   "clave": "dad-2304",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": false,
   "especialidad": "desarrollo"
  },
  {
   "semestre": 8,
   "asignatura": "Programación lógica y funcional",
   "clave": "scc-1019",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 8,
   "asignatura": "Taller de investigación II",
   "clave": "aca-0910",
   "horasTeoricas": 0,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 8,
   "asignatura": "Cultura empresarial",
   "clave": "scs-1005",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 8,
   "asignatura": "Desarrollo sustentable",
   "clave": "acd-0908",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 8,
   "asignatura": "Devops",
   "clave": "dam-2305",
   "horasTeoricas": 2,
   "horasPracticas": 4,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": false,
   "especialidad": "desarrollo"
  },
  {
   "semestre": 9,
   "asignatura": "Inteligencia artificial",
   "clave": "scc-1012",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 9,
   "asignatura": "Graficación",
   "clave": "scc-1010",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": true,
   "grupoVespertino": true,
   "especialidad": false
  },
  {
   "semestre": 6,
   "asignatura": "Seguridad y automatización de redes empresariales",
   "clave": "sed-2301",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": false,
   "grupoVespertino": true,
   "especialidad": "redes"
  },
  {
   "semestre": 6,
   "asignatura": "Gestión de seguridad de las tic",
   "clave": "see-2302",
   "horasTeoricas": 3,
   "horasPracticas": 1,
   "programaEducativo": "isc",
   "grupoMatutino": false,
   "grupoVespertino": true,
   "especialidad": "redes"
  },
  {
   "semestre": 7,
   "asignatura": "Diseño de proyectos de redes empresariales",
   "clave": "sed-2303",
   "horasTeoricas": 2,
   "horasPracticas": 3,
   "programaEducativo": "isc",
   "grupoMatutino": false,
   "grupoVespertino": true,
   "especialidad": "redes"
  },
  {
   "semestre": 7,
   "asignatura": "Seguridad de la infraestructura tecnológica",
   "clave": "sec-2304",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": false,
   "grupoVespertino": true,
   "especialidad": "redes"
  },
  {
   "semestre": 7,
   "asignatura": "Cómputo en la nube con ms azure",
   "clave": "seq-2305",
   "horasTeoricas": 1,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": false,
   "grupoVespertino": true,
   "especialidad": "redes"
  },
  {
   "semestre": 8,
   "asignatura": "Cómputo en la nube con aws",
   "clave": "sec-2306",
   "horasTeoricas": 2,
   "horasPracticas": 2,
   "programaEducativo": "isc",
   "grupoMatutino": false,
   "grupoVespertino": true,
   "especialidad": "redes"
  }
 ]
